// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_f_a27sKChfa8NNhAWygLWmvAvmSFQ-E',
    appId: '1:478796578778:web:47c8f436c1d40cf4628ae3',
    messagingSenderId: '478796578778',
    projectId: 'my-contacts-fire',
    authDomain: 'my-contacts-fire.firebaseapp.com',
    storageBucket: 'my-contacts-fire.firebasestorage.app',
    measurementId: 'G-39LC4FE357',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8rBm8NYz3M6L9kOVkDOYwz6oufFS_MgM',
    appId: '1:478796578778:android:7f1bc6ca4bbd5cd8628ae3',
    messagingSenderId: '478796578778',
    projectId: 'my-contacts-fire',
    storageBucket: 'my-contacts-fire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPiyS9MJ-yM0DPVfJ1fE2ktvPgY-BvhCc',
    appId: '1:478796578778:ios:d3418246228300bd628ae3',
    messagingSenderId: '478796578778',
    projectId: 'my-contacts-fire',
    storageBucket: 'my-contacts-fire.firebasestorage.app',
    iosBundleId: 'com.example.myContactsFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPiyS9MJ-yM0DPVfJ1fE2ktvPgY-BvhCc',
    appId: '1:478796578778:ios:d3418246228300bd628ae3',
    messagingSenderId: '478796578778',
    projectId: 'my-contacts-fire',
    storageBucket: 'my-contacts-fire.firebasestorage.app',
    iosBundleId: 'com.example.myContactsFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_f_a27sKChfa8NNhAWygLWmvAvmSFQ-E',
    appId: '1:478796578778:web:19b1025e583ea5ad628ae3',
    messagingSenderId: '478796578778',
    projectId: 'my-contacts-fire',
    authDomain: 'my-contacts-fire.firebaseapp.com',
    storageBucket: 'my-contacts-fire.firebasestorage.app',
    measurementId: 'G-NLFR2TG02S',
  );
}
